### ISSUE TITLE
Switches not properly created

### ISSUE THREAD

**Issue by gmiotto** [mpeuster/dockernet#4] opened 2016-01-19 12:49 UTC
When running the command: `sudo mn` (does not matter which topo options are used), the switches are not properly created. They do not connect to the controller, the `ovs-vsctl show` command does not display information about the bridges and with the `ovs-ofctl dump-flows s1` output says that such bridge does not exist.
 When tested with mininet itself, it works correctly. I tried to merge the latest mininet on dockernet, but the error persists.

**Comment by mpeuster** [comment] 2016-01-19 13:44
Hi! Thanks for reporting this.

With which topology did you try this? For now, the Dockernet specific APIs are only implemented for the low level APIs. Not for all. For example, I never had the time to test it with the predefined TreeTopologies etc.

It was typically tested with the example in https://github.com/mpeuster/dockernet/blob/master/examples/dockerhosts.py

Does this work for you?

**Comment by gmiotto** [comment] 2016-01-19 15:18
The dockerhosts.py works correctly for me, the script that I was also using works correctly. The problem arose when I attempted to use the switches in inband mode, at this point I realise the problem.
I am also using Ubuntu 14.04; I did the unit tests and the result is this:
```bash
dockernet/mininet$ sudo python test -d -v
testDockerDocker (test_dockernet.testDockernetConnectivity) ... ok
testDockerMultipleInterfaces (test_dockernet.testDockernetConnectivity) ... ok
testDockerSwtichDocker (test_dockernet.testDockernetConnectivity) ... ok
testHostDocker (test_dockernet.testDockernetConnectivity) ... ok
testHostSwtichDocker (test_dockernet.testDockernetConnectivity) ... ok
testCommandSimple (test_dockernet.testDockernetContainerCommandExecution) ... ok
testCPULimitCFSBased (test_dockernet.testDockernetContainerResourceLimitAPI) ... ok
testCPUShare (test_dockernet.testDockernetContainerResourceLimitAPI) ... ok
testMemLimits (test_dockernet.testDockernetContainerResourceLimitAPI) ... ok
testFullyDynamic (test_dockernet.testDockernetDynamicTopologies) ... Error setting d1-eth0 up: ifconfig d1-eth0 up Error setting d2-eth0 up: ifconfig d2-eth0 up ok
testSimpleAdd (test_dockernet.testDockernetDynamicTopologies) ... ok
testSimpleRemove (test_dockernet.testDockernetDynamicTopologies) ... Error setting d0-eth0 up: ifconfig d0-eth0 up ok
testCustomDelay (test_dockernet.testDockernetTCLinks) ... ok
testCustomLoss (test_dockernet.testDockernetTCLinks) ... ok

----------------------------------------------------------------------
Ran 14 tests in 50.256s

OK
```
Might these errors be affecting the functionality?

**Comment by mpeuster** [comment] 2016-01-21 15:57
The errors in the unit tests shouldn't be a problem.

I tried to set the switches to inband mode by changing the dockerhosts.py to:

    s1 = net.addSwitch('s1', cls=OVSSwitch, inband=True)
    s2 = net.addSwitch('s2', cls=OVSSwitch, inband=True)
    s3 = net.addSwitch('s3', cls=OVSSwitch, inband=True)

When I then use:

sudo ovs-vsctl show

I get, as normal:

Bridge "s2"
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        fail_mode: secure
        Port "s2-eth2"
            Interface "s2-eth2"
        Port "s2-eth1"
            Interface "s2-eth1"
        Port "s2-eth3"
            Interface "s2-eth3"
        Port "s2"
            Interface "s2"
                type: internal
    Bridge "s1"
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        fail_mode: secure
        Port "s1-eth3"
            Interface "s1-eth3"
        Port "s1"
            Interface "s1"
                type: internal
        Port "s1-eth1"
            Interface "s1-eth1"
        Port "s1-eth2"
            Interface "s1-eth2"
        Port "s1-eth4"
            Interface "s1-eth4"
    Bridge "s3"
        Controller "tcp:127.0.0.1:6633"
            is_connected: true
        fail_mode: secure
        Port "s3-eth1"
            Interface "s3-eth1"
        Port "s3"
            Interface "s3"
                type: internal
        Port "s3-eth2"
            Interface "s3-eth2"
    ovs_version: "2.0.2"

The command ovs-ofctl dump-flows s1 also works fine and I can see the ICMP traffic when I do d1 ping -c 20 d2.

So I am not sure how to reproduce the problem?

**Comment by mpeuster** [comment] 2016-01-21 16:06
What I can confirm that the switches are not created when using, e.g., `sudo ./mn --switch=ovs -topo=linear`.

Not sure where it breaks. I never checked this since I didn't need it for my use cases. Will look into it if I can find some time.

**Comment by mpeuster** [comment] 2016-01-21 16:18
I guess I fixed it by disabling switch batch startup in net.py:

    #if hasattr( cls, 'batchStartup' ):
    #    params.setdefault( 'batch', True )
    
I committed this change 7fe5e08b1a2dcd4366a0f71348416e949970e613.

**Closed** 2016-01-21 18:13 UTC
